### ISSUE TITLE
Can't start up local Firebase.  

### ISSUE THREAD

**Issue by xcollantes** [Respond-Crisis-Translation/rct-portal#42]
I'm looking to test my changes on my local machine by starting up http://localhost:5000/.  

I ran instructions on the repo's front page: 
```
npm run-script build
firebase emulators:start
```
Start up was successful: https://gist.github.com/xcollantes/76cd3c5bc254969d8746e72ec5be756d 

But when visiting http://localhost:5000/, I was greeted with a blank page.  

I tried `yarn build` with the same result.  

Is there any idea what I can do to get the local site going?  Thank you!  Much appreciated.

**Comment by YogenRaii** [comment]
Hi @xcollantes , would you mind sharing the log that you can see on chrome developer console? 

Btw, you can use key from rct-portal--dev and run against dev firebase instance! we can break anything we want on this :)

**Comment by xcollantes** [comment]
Ah, that gave me enough of a hint.  With that I'm able to log in with a test account :)  Thank you!  
I'll add `firebase.json` to my .gitignore.  Since the credentials are stored there.
